def interactive_quiz():
    questions = [
        ("What is the capital of France?", "Paris"),
        ("What is 2 + 2?", "4"),
        ("What is the largest planet in our solar system?", "Jupiter"),
        ("Who wrote 'To Kill a Mockingbird'?", "Harper Lee"),
        ("What is the chemical symbol for gold?", "Au"),
        ("Who painted the Mona Lisa?", "Leonardo da Vinci"),
        ("What is the smallest country in the world?", "Vatican City"),
        ("What is the capital of Japan?", "Tokyo"),
        ("How many continents are there?", "7"),
        ("What is the tallest mountain in the world?", "Mount Everest"),
        ("Who developed the theory of relativity?", "Albert Einstein"),
        ("What is the largest ocean on Earth?", "Pacific Ocean"),
        ("What is the hardest natural substance?", "Diamond"),
        ("What is the currency of the United Kingdom?", "Pound"),
        ("Who wrote the play 'Romeo and Juliet'?", "William Shakespeare"),
        ("What is the capital of Australia?", "Canberra"),
        ("What is the square root of 64?", "8"),
        ("What is the longest river in the world?", "Nile"),
        ("Who was the first president of the United States?", "George Washington"),
        ("What is the chemical formula for water?", "H2O"),
        ("Who discovered penicillin?", "Alexander Fleming"),
        ("What is the capital of Canada?", "Ottawa"),
        ("What planet is known as the Red Planet?", "Mars"),
        ("What is the largest mammal in the world?", "Blue whale"),
        ("Who painted the ceiling of the Sistine Chapel?", "Michelangelo"),
        ("What is the speed of light?", "299,792,458 meters per second"),
        ("What is the capital of Italy?", "Rome"),
        ("Who wrote '1984'?", "George Orwell"),
        ("What is the boiling point of water in Celsius?", "100"),
        ("Who is known as the father of computers?", "Charles Babbage"),
        ("What is the largest desert in the world?", "Sahara"),
        ("What is the capital of Brazil?", "Brasília"),
        ("What is the main ingredient in guacamole?", "Avocado"),
        ("Who invented the telephone?", "Alexander Graham Bell"),
        ("What is the largest bone in the human body?", "Femur"),
        ("What is the capital of Russia?", "Moscow"),
        ("What element does 'O' represent on the periodic table?", "Oxygen"),
        ("Who wrote 'Pride and Prejudice'?", "Jane Austen"),
        ("What is the smallest prime number?", "2"),
        ("What is the capital of India?", "New Delhi"),
        ("What is the largest land animal?", "Elephant"),
        ("Who discovered America?", "Christopher Columbus"),
        ("What is the capital of Egypt?", "Cairo"),
        ("What is the largest island in the world?", "Greenland"),
        ("Who wrote 'Moby-Dick'?", "Herman Melville"),
        ("What is the primary gas in the Earth's atmosphere?", "Nitrogen"),
        ("What is the capital of Germany?", "Berlin"),
        ("What is the longest bone in the human body?", "Femur"),
        ("Who was the first man to walk on the moon?", "Neil Armstrong"),
        ("What is the capital of Spain?", "Madrid"),
        ("What is the capital of China?", "Beijing"),
        ("What is the chemical symbol for silver?", "Ag"),
        ("What is the highest waterfall in the world?", "Angel Falls"),
        ("What is the capital of Mexico?", "Mexico City"),
        ("Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald"),
        ("What is the smallest ocean in the world?", "Arctic Ocean"),
        ("What is the capital of South Korea?", "Seoul"),
        ("What is the first element on the periodic table?", "Hydrogen"),
        ("Who wrote 'The Catcher in the Rye'?", "J.D. Salinger"),
        ("What is the capital of Argentina?", "Buenos Aires"),
        ("What is the largest organ in the human body?", "Skin"),
        ("What is the capital of Saudi Arabia?", "Riyadh"),
        ("Who was the first woman to win a Nobel Prize?", "Marie Curie"),
        ("What is the capital of Turkey?", "Ankara"),
        ("Who wrote 'The Odyssey'?", "Homer"),
        ("What is the chemical symbol for iron?", "Fe"),
        ("What is the capital of Sweden?", "Stockholm"),
        ("Who wrote 'War and Peace'?", "Leo Tolstoy"),
        ("What is the capital of Norway?", "Oslo"),
        ("Who painted 'Starry Night'?", "Vincent van Gogh"),
        ("What is the capital of Kenya?", "Nairobi"),
        ("What is the highest mountain in North America?", "Denali"),
        ("What is the capital of Greece?", "Athens"),
        ("Who wrote 'Crime and Punishment'?", "Fyodor Dostoevsky"),
        ("What is the capital of Portugal?", "Lisbon"),
        ("Who is known as the father of geometry?", "Euclid"),
        ("What is the capital of Chile?", "Santiago"),
        ("What is the largest fish in the ocean?", "Whale shark"),
        ("What is the capital of New Zealand?", "Wellington"),
        ("Who wrote 'Jane Eyre'?", "Charlotte Brontë"),
        ("What is the capital of Peru?", "Lima"),
        ("What is the most abundant element in the universe?", "Hydrogen"),
        ("What is the capital of Iraq?", "Baghdad"),
        ("Who wrote 'The Iliad'?", "Homer"),
        ("What is the capital of the Netherlands?", "Amsterdam"),
        ("What is the largest bird in the world?", "Ostrich"),
        ("What is the capital of Finland?", "Helsinki"),
        ("Who wrote 'Great Expectations'?", "Charles Dickens"),
        ("What is the capital of Indonesia?", "Jakarta"),
        ("What is the largest artery in the human body?", "Aorta"),
        ("What is the capital of Iran?", "Tehran"),
        ("Who wrote 'Frankenstein'?", "Mary Shelley"),
        ("What is the capital of Thailand?", "Bangkok"),
        ("What is the largest muscle in the human body?", "Gluteus maximus"),
        ("What is the capital of Ukraine?", "Kyiv"),
        ("Who wrote 'Don Quixote'?", "Miguel de Cervantes"),
        ("What is the capital of Poland?", "Warsaw"),
        ("What is the capital of Denmark?", "Copenhagen"),
        ("Who wrote 'The Divine Comedy'?", "Dante Alighieri"),
        ("What is the capital of Switzerland?", "Bern"),
        ("Who invented the World Wide Web?", "Tim Berners-Lee"),
    ]
    score = 0
    for question, correct_answer in questions:
        user_answer = input(question + " ")
        if user_answer.lower() == correct_answer.lower():
            score += 1
            print("Correct!")
        else:
            print("Wrong!")
    print(f"Your final score is {score}/{len(questions)}")

interactive_quiz()